services:
  redis:
    image: redis:6-alpine
    restart: always
    ports:
      - '6379:6379'

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:api
    ports:
      - '3000:3000'
    env_file:
      - ./.env
    depends_on:
      - redis
    restart: always
    volumes:
      - ./sessions:/usr/src/app/sessions
      - ./data:/usr/src/app/data
      - ./uploads:/usr/src/app/uploads

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:worker
    env_file:
      - ./.env
    depends_on:
      - redis
    restart: always
    volumes:
      - ./sessions:/usr/src/app/sessions
      - ./data:/usr/src/app/data
      - ./uploads:/usr/src/app/uploads
